<a href="https://colab.research.google.com/github/sabrinaangel/ml-dataset-preprocessing/blob/main/Week%207/ann_tabularDatasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [ ]:
dataset

In [ ]:
print(X)

In [ ]:
print(y)

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = ColumnTransformer([('one_hot_encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = onehotencoder.fit_transform(X)
X = X[:, 1:]

In [ ]:
print(X)

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Now let's make the ANN!

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Initialising the ANN
classifier = Sequential()

In [ ]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [40]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7958 - loss: 0.4914
Epoch 2/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7960 - loss: 0.4300
Epoch 3/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7960 - loss: 0.4254
Epoch 4/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8059 - loss: 0.4212
Epoch 5/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8235 - loss: 0.4181
Epoch 6/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8278 - loss: 0.4159
Epoch 7/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8281 - loss: 0.4141
Epoch 8/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8310 - loss: 0.4125
Epoch 9/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8313 - loss: 0.4116
Epoch 10/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8317 - loss: 0.4106
Epoch 11/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8321 - loss: 0.4099
Epoch 12/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step

Making predictions and evaluating the model

In [41]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred_ = (y_pred > 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [42]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_)

In [43]:
cm

array([[1541,   54],
       [ 265,  140]])

In [44]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [45]:
y_pred_

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [46]:
y_pred

array([[0.24651083],
       [0.36826378],
       [0.21882972],
       ...,
       [0.20605625],
       [0.18751016],
       [0.14832239]], dtype=float32)

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred_)
print("Confusion Matrix:\n", cm)

# Menghitung metrik performa
accuracy = accuracy_score(y_test, y_pred_)
precision = precision_score(y_test, y_pred_)
recall = recall_score(y_test, y_pred_)
f1 = f1_score(y_test, y_pred_)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Confusion Matrix:
 [[1541   54]
 [ 265  140]]
Accuracy: 0.8405
Precision: 0.7216494845360825
Recall: 0.345679012345679
F1 Score: 0.4674457429048414


**## Eksperimen Baru: ANN dengan Dropout Layer**

In [48]:
from keras.layers import Dropout

# Initialising the ANN with Dropout
classifier_dropout = Sequential()

# Adding the input layer and the first hidden layer with Dropout
classifier_dropout.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
classifier_dropout.add(Dropout(rate = 0.1))

# Adding the second hidden layer with Dropout
classifier_dropout.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier_dropout.add(Dropout(rate = 0.1))

# Adding the output layer
classifier_dropout.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier_dropout.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


**### Melatih Model ANN Baru**

In [49]:
# Fitting the new ANN with Dropout to the Training set
classifier_dropout.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7956 - loss: 0.5005
Epoch 2/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7960 - loss: 0.4404
Epoch 3/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7960 - loss: 0.4355
Epoch 4/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8008 - loss: 0.4310
Epoch 5/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8174 - loss: 0.4297
Epoch 6/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8207 - loss: 0.4279
Epoch 7/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8242 - loss: 0.4241
Epoch 8/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8230 - loss: 0.4262
Epoch 9/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8256 - loss: 0.4231
Epoch 10/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8226 - loss: 0.4191
Epoch 11/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8225 - loss: 0.4202
Epoch 12/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

**### Membuat Prediksi dan Mengevaluasi Model ANN Baru**

In [50]:
# Predicting the Test set results with the new model
y_pred_dropout = classifier_dropout.predict(X_test)
y_pred_dropout_ = (y_pred_dropout > 0.5)

# Making the Confusion Matrix for the new model
cm_dropout = confusion_matrix(y_test, y_pred_dropout_)
print("Confusion Matrix (with Dropout):\n", cm_dropout)

# Menghitung metrik performa untuk model baru
accuracy_dropout = accuracy_score(y_test, y_pred_dropout_)
precision_dropout = precision_score(y_test, y_pred_dropout_)
recall_dropout = recall_score(y_test, y_pred_dropout_)
f1_dropout = f1_score(y_test, y_pred_dropout_)

print("\n--- Performa Model ANN dengan Dropout ---")
print("Accuracy:", accuracy_dropout)
print("Precision:", precision_dropout)
print("Recall:", recall_dropout)
print("F1 Score:", f1_dropout)

print("\n--- Perbandingan dengan Model Asli ---")
print(f"Accuracy Asli: {accuracy:.4f}, Accuracy Dropout: {accuracy_dropout:.4f}")
print(f"Precision Asli: {precision:.4f}, Precision Dropout: {precision_dropout:.4f}")
print(f"Recall Asli: {recall:.4f}, Recall Dropout: {recall_dropout:.4f}")
print(f"F1 Score Asli: {f1:.4f}, F1 Score Dropout: {f1_dropout:.4f}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Confusion Matrix (with Dropout):
 [[1548   47]
 [ 270  135]]

--- Performa Model ANN dengan Dropout ---
Accuracy: 0.8415
Precision: 0.7417582417582418
Recall: 0.3333333333333333
F1 Score: 0.4599659284497445

--- Perbandingan dengan Model Asli ---
Accuracy Asli: 0.8405, Accuracy Dropout: 0.8415
Precision Asli: 0.7216, Precision Dropout: 0.7418
Recall Asli: 0.3457, Recall Dropout: 0.3333
F1 Score Asli: 0.4674, F1 Score Dropout: 0.4600
